### ISSUE TITLE
Client Leaves Channel Randomly

### ISSUE THREAD

**Issue by Bappsack** [TwitchLib/TwitchLib.Client#123] opened 2019-10-26 12:17 UTC
Ran into something strange with latest Dev Branch:

Client disconnects randomly, not a big issue, able to reconnect fine.

FollowerService & PubSub doesnt disconnect at all.

but recently the client just leaves the channel somehow, doesnt trigger any events (OnLeft Channel/OnError/etc.)

if the client leaves the channel somehow it triggers the exception while trying to send a message:

```Must be connected to at least one channel.```

if i try catch it, to let it rejoin the channel this sorta works, but sometimes it triggers the Exception:

```In order to perform this action, the client must be connected to Twitch. To confirm connection, try performing this action in or after the OnConnected event has been fired.```

currently going back to stable branch to see if there is the same issue:

Code is just the usual:

```
 public async Task RunBot()
        {
            try
            {
                ConnectionCredentials credentials = new ConnectionCredentials("****", OAuth);
                client = new TwitchClient();
                client.Initialize(credentials, joinedchannel);
                client.Connect();
                
                client.OnMessageReceived += OnMessageReceived;
                client.OnDisconnected += OnDisconnected;
                client.OnLeftChannel += OnLeftChannel;
                client.OnError += OnError;

                client.OnJoinedChannel += OnJoinenChannel;
                client.OnConnected += OnConnected;

                await Task.Delay(-1);

            }
        }

private void OnJoinenChannel(object sender, OnJoinedChannelArgs e)
        {
            // ApplyLog("Successfull connected to Live Stream: " + e.Channel + ".");
        }

private void OnError(object sender, OnErrorEventArgs e)
        {
                    client.JoinChannel(joinedchannel);
        }

private void OnLeftChannel(object sender, OnLeftChannelArgs e)
        {
                client.JoinChannel(joinedchannel);
        }

private async void OnConnected(object sender, OnConnectedArgs e)
        {
                //client.JoinChannel(joinedchannel, false);
        }

 private async void OnDisconnected(object sender, TwitchLib.Communication.Events.OnDisconnectedEventArgs e)
        {
                if (!client.IsConnected)
                {
                    ApplyLog("Chatbot disconnected,Connection lost! Trying to Reconnect...");
                  
                        while (!client.IsConnected)
                        {
                            client.Connect();
                            await Task.Delay(5000);
                        }
               }
        }
```

**Comment by Bappsack** [comment] 2019-10-26 15:22
same issue on Stable Branch, it seems the client somehow just leaves the channel.

**Comment by Bappsack** [comment] 2019-10-27 09:39
Issue solved now, not 100% sure but my bets rely on the recent Win Update & their Firewall.

**Comment by Bappsack** [comment] 2019-10-28 20:02
leaving this now open again, since its still present.

**Comment by swiftyspiffy** [comment] 2019-10-29 09:28
Later today will start a simple bot and host it on an ec2 instance and see see if the issue is encountered.

**Comment by Bappsack** [comment] 2019-10-29 22:26
Starting to think its on my end tho, literally just updated Windows on Stream PC, also need to mention that i replaced my isp router, but don't think its related to the router cuz it works like a charm no disconnects at all in the past 48h.

solved Disconnects with a hacky Reconnect now, but still wondering why the Bot leave the channel without triggering the OnChannelLeft Event, also dont fire Follower/PubSub Disconnect Events on regular disconnect.

**Comment by swiftyspiffy** [comment] 2019-11-23 02:52
Can you give the dev branch a try? I'm interested to see if it still persists.

**Comment by Bappsack** [comment] 2019-11-30 13:50
@swiftyspiffy recent changes on dev branch arent on nuget yet.

**Comment by Mahsaap** [comment] 2019-11-30 13:53
Individual package pre release. The packaged suite wont have it. Any commits, do get auto pushed to pre release. Since master seems higher then pre release tho you might have to select the CI from the dropdown

**Comment by Mahsaap** [comment] 2019-11-30 13:53
Last push was 8 days ago

**Comment by Mahsaap** [comment] 2019-11-30 13:54
Or remove yours and use Install-Package TwitchLib.Client -Version 3.0.6-CI-20191122-060155

**Comment by Bappsack** [comment] 2019-11-30 14:02
will try after work, i'll let u know if the problem still exist.

**Comment by Bappsack** [comment] 2019-12-19 15:20
still exist, sorry for the delay.

**Comment by Syzuna** [comment] 2020-07-18 21:52
There were no new mesages to this issue for over half a year.
Assuming it was fixed during that time.
Going ahead and closing this issue.

Feel free to reopen if further assistance is required.

**Closed by Syzuna** 2020-07-18 21:52 UTC
